package FactSL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class EntityType_Constraints extends BaseConstraintsDescriptor {
  public EntityType_Constraints() {
    super(MetaAdapterFactory.getConcept(0x6836a913df904e79L, 0x9a37cb334bb02ea5L, 0x2613bb9aeaa7c0a6L, "FactSL.structure.EntityType"));
  }

}
