package AWSStateMachine.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBooleanValue = createDescriptorForBooleanValue();
  /*package*/ final ConceptDescriptor myConceptChoiceRule = createDescriptorForChoiceRule();
  /*package*/ final ConceptDescriptor myConceptComparison = createDescriptorForComparison();
  /*package*/ final ConceptDescriptor myConceptIntegerValue = createDescriptorForIntegerValue();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptStateInput = createDescriptorForStateInput();
  /*package*/ final ConceptDescriptor myConceptStateMachine = createDescriptorForStateMachine();
  /*package*/ final ConceptDescriptor myConceptStringValue = createDescriptorForStringValue();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();
  /*package*/ final ConceptDescriptor myConceptVariableReference = createDescriptorForVariableReference();
  /*package*/ final EnumerationDescriptor myEnumerationComparisonOperators = new EnumerationDescriptor_ComparisonOperators();
  /*package*/ final EnumerationDescriptor myEnumerationStateType = new EnumerationDescriptor_StateType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBooleanValue, myConceptChoiceRule, myConceptComparison, myConceptIntegerValue, myConceptState, myConceptStateInput, myConceptStateMachine, myConceptStringValue, myConceptValue, myConceptVariable, myConceptVariableReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BooleanValue:
        return myConceptBooleanValue;
      case LanguageConceptSwitch.ChoiceRule:
        return myConceptChoiceRule;
      case LanguageConceptSwitch.Comparison:
        return myConceptComparison;
      case LanguageConceptSwitch.IntegerValue:
        return myConceptIntegerValue;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.StateInput:
        return myConceptStateInput;
      case LanguageConceptSwitch.StateMachine:
        return myConceptStateMachine;
      case LanguageConceptSwitch.StringValue:
        return myConceptStringValue;
      case LanguageConceptSwitch.Value:
        return myConceptValue;
      case LanguageConceptSwitch.Variable:
        return myConceptVariable;
      case LanguageConceptSwitch.VariableReference:
        return myConceptVariableReference;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationComparisonOperators, myEnumerationStateType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBooleanValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "BooleanValue", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bbdL);
    b.class_(false, false, false);
    b.super_("AWSStateMachine.structure.Value", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb3L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/40305210172459965");
    b.version(2);
    b.property("value", 0x8f316006ed4bbeL).type(PrimitiveTypeId.BOOLEAN).origin("40305210172459966").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChoiceRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "ChoiceRule", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad44f4aL);
    b.class_(false, false, false);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617394380618");
    b.version(2);
    b.associate("Next", 0x4c74ef895ad71a29L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L).optional(false).origin("5509291617394563625").done();
    b.aggregate("Comparison", 0x4c74ef895ad5ea2dL).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f71L).optional(false).ordered(true).multiple(false).origin("5509291617394485805").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComparison() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "Comparison", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f71L);
    b.class_(false, false, false);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617394397041");
    b.version(2);
    b.property("Operator", 0x4c74ef895ad48f74L).type(MetaIdFactory.dataTypeId(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad44d0aL)).origin("5509291617394397044").done();
    b.associate("Variable", 0x4c74ef895ad89219L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f7bL).optional(false).origin("5509291617394659865").done();
    b.aggregate("value", 0x8f316006eef289L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb3L).optional(false).ordered(true).multiple(false).origin("40305210172568201").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntegerValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "IntegerValue", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bc3L);
    b.class_(false, false, false);
    b.super_("AWSStateMachine.structure.Value", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb3L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/40305210172459971");
    b.version(2);
    b.property("value", 0x8f316006ed4bc4L).type(PrimitiveTypeId.INTEGER).origin("40305210172459972").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "State", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617393485093");
    b.version(2);
    b.property("Type", 0x4c74ef895ac6a55cL).type(MetaIdFactory.dataTypeId(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a539L)).origin("5509291617393485148").done();
    b.property("End", 0x4c74ef895ac6a55eL).type(PrimitiveTypeId.BOOLEAN).origin("5509291617393485150").done();
    b.property("Comment", 0x4c74ef895ac6a563L).type(PrimitiveTypeId.STRING).origin("5509291617393485155").done();
    b.property("Resource", 0x4c74ef895b02598bL).type(PrimitiveTypeId.STRING).origin("5509291617397397899").done();
    b.property("TimeoutSeconds", 0x4c74ef895b025990L).type(PrimitiveTypeId.INTEGER).origin("5509291617397397904").done();
    b.property("HeartbeatSecond", 0x4c74ef895b025996L).type(PrimitiveTypeId.INTEGER).origin("5509291617397397910").done();
    b.associate("Next", 0x4c74ef895ad09b96L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L).optional(true).origin("5509291617394138006").done();
    b.associate("Default", 0x4c74ef895ad44f4eL).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L).optional(true).origin("5509291617394380622").done();
    b.aggregate("StateInput", 0x4c74ef895ad7d437L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad7d402L).optional(true).ordered(true).multiple(false).origin("5509291617394611255").done();
    b.aggregate("Choices", 0x4c74ef895ad5ea29L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad44f4aL).optional(true).ordered(true).multiple(true).origin("5509291617394485801").done();
    b.aggregate("Branches", 0x4c74ef895af67b52L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a51fL).optional(true).ordered(true).multiple(true).origin("5509291617396620114").done();
    b.aggregate("Parameters", 0x51bd09cd96a80d41L).target(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d576L).optional(true).ordered(true).multiple(false).origin("5889874666271018305").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStateInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "StateInput", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad7d402L);
    b.class_(false, false, false);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617394611202");
    b.version(2);
    b.aggregate("Variables", 0x4c74ef895ad7d403L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f7bL).optional(true).ordered(true).multiple(true).origin("5509291617394611203").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStateMachine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "StateMachine", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a51fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617393485087");
    b.version(2);
    b.property("Comment", 0x4c74ef895ac6a520L).type(PrimitiveTypeId.STRING).origin("5509291617393485088").done();
    b.property("TimeoutSeconds", 0x4c74ef895ac6a52fL).type(PrimitiveTypeId.INTEGER).origin("5509291617393485103").done();
    b.property("Version", 0x4c74ef895ac6a532L).type(PrimitiveTypeId.STRING).origin("5509291617393485106").done();
    b.associate("StartAt", 0x4c74ef895ac85bbaL).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L).optional(false).origin("5509291617393597370").done();
    b.aggregate("States", 0x4c74ef895ac6a536L).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ac6a525L).optional(true).ordered(true).multiple(true).origin("5509291617393485110").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStringValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "StringValue", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb7L);
    b.class_(false, false, false);
    b.super_("AWSStateMachine.structure.Value", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb3L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/40305210172459959");
    b.version(2);
    b.property("value", 0x8f316006ed4bb8L).type(PrimitiveTypeId.STRING).origin("40305210172459960").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "Value", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x8f316006ed4bb3L);
    b.class_(false, true, false);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/40305210172459955");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "Variable", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f7bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617394397051");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariableReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("AWSStateMachine", "VariableReference", 0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f7eL);
    b.class_(false, false, false);
    b.origin("r:393117f7-cc47-4543-83a6-7f3b110b90e7(AWSStateMachine.structure)/5509291617394397054");
    b.version(2);
    b.associate("variable", 0x4c74ef895ad48f7fL).target(0xad34076bb44b4b8eL, 0x9aa6566fa22fe764L, 0x4c74ef895ad48f7bL).optional(false).origin("5509291617394397055").done();
    return b.create();
  }
}
