language: java
jdk:
- oraclejdk8
before_install:
- wget https://download-cf.jetbrains.com/mps/2018.2/MPS-2018.2.zip
- wget https://guest:@build.mbeddr.com/repository/downloadAll/Mbeddr2_Mbeddr_Gradle_platform/138020:id/artifacts.zip
install: 
- unzip MPS-2018.2.zip
- unzip artifacts.zip
script: ant -Dmps_home=./MPS\ 2018.2 -Dmbeddr_home=./com.mbeddr.platform -Durl_home=.
