package DemoSL.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class Case {
  /*package*/ Integer caseID;
  /*package*/ SNode currentStepKind;


  /*package*/ void startCase(Integer id, SNode stepKind) {
    caseID = id;
    currentStepKind = stepKind;
  }
}
