package ProcessSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptLink = createDescriptorForLink();
  /*package*/ final ConceptDescriptor myConceptTransactionKindStepKind = createDescriptorForTransactionKindStepKind();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptLink, myConceptTransactionKindStepKind);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Link:
        return myConceptLink;
      case LanguageConceptSwitch.TransactionKindStepKind:
        return myConceptTransactionKindStepKind;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ProcessSL", "Link", 0xa2c2ae097c364fbaL, 0x9b645e0450cb1363L, 0x585f5ae0f86c841L);
    b.class_(false, false, false);
    b.origin("r:5ab429eb-39f0-410d-aa8d-fa3ed3e71aa4(ProcessSL.structure)/397994270025762881");
    b.version(2);
    b.prop("linkType", 0x2e078028fdab53bdL, "3316760564124570557");
    b.associate("transactionKindStepKindFrom", 0x585f5ae0f86c847L).target(0xa2c2ae097c364fbaL, 0x9b645e0450cb1363L, 0x585f5ae0f86c73eL).optional(false).origin("397994270025762887").done();
    b.associate("transactionKindStepKindTo", 0x585f5ae0f86c842L).target(0xa2c2ae097c364fbaL, 0x9b645e0450cb1363L, 0x585f5ae0f86c73eL).optional(false).origin("397994270025762882").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransactionKindStepKind() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ProcessSL", "TransactionKindStepKind", 0xa2c2ae097c364fbaL, 0x9b645e0450cb1363L, 0x585f5ae0f86c73eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5ab429eb-39f0-410d-aa8d-fa3ed3e71aa4(ProcessSL.structure)/397994270025762622");
    b.version(2);
    b.prop("stepKind", 0x585f5ae0f86c7e6L, "397994270025762790");
    b.prop("revoke", 0x585f5ae0f86c7ebL, "397994270025762795");
    b.prop("revokeKind", 0x585f5ae0f86c7e8L, "397994270025762792");
    b.associate("transactionKind", 0x585f5ae0f86c73fL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f05L).optional(false).origin("397994270025762623").done();
    return b.create();
  }
}
