package ConstructionSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAbstractActorRole = createDescriptorForAbstractActorRole();
  /*package*/ final ConceptDescriptor myConceptAbstractTransactionKind = createDescriptorForAbstractTransactionKind();
  /*package*/ final ConceptDescriptor myConceptActorRole = createDescriptorForActorRole();
  /*package*/ final ConceptDescriptor myConceptActorRoleReference = createDescriptorForActorRoleReference();
  /*package*/ final ConceptDescriptor myConceptAggregateTransactionKind = createDescriptorForAggregateTransactionKind();
  /*package*/ final ConceptDescriptor myConceptCompositeActorRole = createDescriptorForCompositeActorRole();
  /*package*/ final ConceptDescriptor myConceptCompositeActorRoleReference = createDescriptorForCompositeActorRoleReference();
  /*package*/ final ConceptDescriptor myConceptExecutor = createDescriptorForExecutor();
  /*package*/ final ConceptDescriptor myConceptInitiator = createDescriptorForInitiator();
  /*package*/ final ConceptDescriptor myConceptScopeOfInterest = createDescriptorForScopeOfInterest();
  /*package*/ final ConceptDescriptor myConceptTransactionKind = createDescriptorForTransactionKind();
  /*package*/ final ConceptDescriptor myConceptTransactionKindReference = createDescriptorForTransactionKindReference();
  /*package*/ final ConceptDescriptor myConcepttest = createDescriptorFortest();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAbstractActorRole, myConceptAbstractTransactionKind, myConceptActorRole, myConceptActorRoleReference, myConceptAggregateTransactionKind, myConceptCompositeActorRole, myConceptCompositeActorRoleReference, myConceptExecutor, myConceptInitiator, myConceptScopeOfInterest, myConceptTransactionKind, myConceptTransactionKindReference, myConcepttest);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AbstractActorRole:
        return myConceptAbstractActorRole;
      case LanguageConceptSwitch.AbstractTransactionKind:
        return myConceptAbstractTransactionKind;
      case LanguageConceptSwitch.ActorRole:
        return myConceptActorRole;
      case LanguageConceptSwitch.ActorRoleReference:
        return myConceptActorRoleReference;
      case LanguageConceptSwitch.AggregateTransactionKind:
        return myConceptAggregateTransactionKind;
      case LanguageConceptSwitch.CompositeActorRole:
        return myConceptCompositeActorRole;
      case LanguageConceptSwitch.CompositeActorRoleReference:
        return myConceptCompositeActorRoleReference;
      case LanguageConceptSwitch.Executor:
        return myConceptExecutor;
      case LanguageConceptSwitch.Initiator:
        return myConceptInitiator;
      case LanguageConceptSwitch.ScopeOfInterest:
        return myConceptScopeOfInterest;
      case LanguageConceptSwitch.TransactionKind:
        return myConceptTransactionKind;
      case LanguageConceptSwitch.TransactionKindReference:
        return myConceptTransactionKindReference;
      case LanguageConceptSwitch.test:
        return myConcepttest;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAbstractActorRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "AbstractActorRole", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/397994270026076726");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAbstractTransactionKind() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "AbstractTransactionKind", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x47e2fc9cf3d1e5d9L);
    b.class_(false, true, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/5179980272465208793");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActorRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "ActorRole", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa032a9L);
    b.class_(false, false, false);
    b.super_("ConstructionSL.structure.AbstractActorRole", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034489001");
    b.version(2);
    b.prop("id", 0x2613bb9aeaa0eeb7L, "2743742872034537143");
    b.aggregate("isActorRoleIn", 0x2e078028fd61c14cL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2e078028fd647073L).optional(true).ordered(true).multiple(true).origin("3316760564119748940").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActorRoleReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "ActorRoleReference", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2e078028fd531e4eL);
    b.class_(false, false, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/3316760564118789710");
    b.version(2);
    b.associate("actorRole", 0x2e078028fd531e4fL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa032a9L).optional(false).origin("3316760564118789711").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAggregateTransactionKind() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "AggregateTransactionKind", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f0cL);
    b.class_(false, false, false);
    b.super_("ConstructionSL.structure.AbstractTransactionKind", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x47e2fc9cf3d1e5d9L);
    b.parent(0xaa59ea5e1883437fL, 0x95c04dc082aa848cL, 0x2613bb9aeaa032abL);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034578188");
    b.version(2);
    b.prop("id", 0x2613bb9aeaa18f0dL, "2743742872034578189");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCompositeActorRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "CompositeActorRole", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f08L);
    b.class_(false, false, false);
    b.super_("ConstructionSL.structure.AbstractActorRole", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034578184");
    b.version(2);
    b.prop("id", 0x2613bb9aeaa18f0aL, "2743742872034578186");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCompositeActorRoleReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "CompositeActorRoleReference", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2e078028fd647073L);
    b.class_(false, false, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/3316760564119924851");
    b.version(2);
    b.associate("compositeActorRole", 0x2e078028fd647074L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f08L).optional(false).origin("3316760564119924852").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExecutor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "Executor", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x6331c55a1a6904bdL);
    b.class_(false, false, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/7147711074394506429");
    b.version(2);
    b.associate("actorRole", 0x6331c55a1a6904eaL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L).optional(false).origin("7147711074394506474").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInitiator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "Initiator", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x6331c55a1a690446L);
    b.class_(false, false, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/7147711074394506310");
    b.version(2);
    b.associate("actorRole", 0x6331c55a1a690475L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L).optional(false).origin("7147711074394506357").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScopeOfInterest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "ScopeOfInterest", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa69ec1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034909889");
    b.version(2);
    b.aggregate("actorRoles", 0x2613bb9aeaa1a68cL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L).optional(true).ordered(true).multiple(true).origin("2743742872034584204").done();
    b.aggregate("transactions", 0x2613bb9aeaa032b2L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x47e2fc9cf3d1e5d9L).optional(true).ordered(true).multiple(true).origin("2743742872034489010").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransactionKind() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "TransactionKind", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f05L);
    b.class_(false, false, false);
    b.super_("ConstructionSL.structure.AbstractTransactionKind", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x47e2fc9cf3d1e5d9L);
    b.parent(0xaa59ea5e1883437fL, 0x95c04dc082aa848cL, 0x2613bb9aeaa032abL);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034578181");
    b.version(2);
    b.prop("id", 0x2613bb9aeaa18f06L, "2743742872034578182");
    b.prop("type", 0x2613bb9aeaa55dc1L, "2743742872034827713");
    b.associate("usesFacts", 0x2613bb9aeaa55db4L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x585f5ae0f8b9236L).optional(true).origin("2743742872034827700").done();
    b.associate("hasProduct", 0x1ed669b9cb67b3bcL).target(0x6836a913df904e79L, 0x9a37cb334bb02ea5L, 0x2613bb9aeaa7c0a5L).optional(true).origin("2222079712856355772").done();
    b.associate("isPartOf", 0x2613bb9aeaa69f13L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f0cL).optional(true).origin("2743742872034909971").done();
    b.aggregate("initiatorConcept", 0x6331c55a1a69117cL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x6331c55a1a690446L).optional(true).ordered(true).multiple(true).origin("7147711074394509692").done();
    b.aggregate("executorConcept", 0x6331c55a1a69118fL).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x6331c55a1a6904bdL).optional(true).ordered(true).multiple(false).origin("7147711074394509711").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransactionKindReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "TransactionKindReference", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2e078028fd531e54L);
    b.class_(false, false, false);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/3316760564118789716");
    b.version(2);
    b.associate("transactionKind", 0x2e078028fd531e55L).target(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa18f05L).optional(false).origin("3316760564118789717").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ConstructionSL", "test", 0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa1f816L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5856ba20-a6c0-48c8-bbf3-7f39968e4bf4(ConstructionSL.structure)/2743742872034605078");
    b.version(2);
    return b.create();
  }
}
