package GeneralSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_ILowerCaseNamedConcept;
  private ConceptPresentation props_IUpperCaseNamedConcept;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.ILowerCaseNamedConcept:
        if (props_ILowerCaseNamedConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ILowerCaseNamedConcept = cpb.create();
        }
        return props_ILowerCaseNamedConcept;
      case LanguageConceptSwitch.IUpperCaseNamedConcept:
        if (props_IUpperCaseNamedConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_IUpperCaseNamedConcept = cpb.create();
        }
        return props_IUpperCaseNamedConcept;
    }
    return null;
  }
}
