package GeneralSL.editor;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import org.jetbrains.annotations.Nullable;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.geom.GeneralPath;
import java.awt.BasicStroke;
import java.awt.Color;

public class Entity extends AbstractShape {


  public Entity() {
  }

  @Nullable
  @Override
  public Double getDefaultSize() {
    return ((double) (15));
  }



  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    GeneralPath shape = new GeneralPath();
    double width = bounds.getWidth();
    double height = bounds.getHeight();
    double x = bounds.getX();
    double y = bounds.getY();
    double r = 10;
    shape.moveTo(x, y + r);
    shape.lineTo(x, y + height - r);
    shape.curveTo(x, y + height, x, y + height, x + r, y + height);
    shape.lineTo(x + width - r, y + height);
    shape.curveTo(x + width, y + height, x + width, y + height, x + width, y + height - r);
    shape.lineTo(x + width, y + r);
    shape.curveTo(x + width, y, x + width, y, x + width - r, y);
    shape.lineTo(x + r, y);
    shape.curveTo(x, y, x, y, x, y + r);

    shape.closePath();
    graphics.setStroke(new BasicStroke(2));
    graphics.setColor(new Color(147, 9, 4));
    graphics.draw(shape);
    graphics.setColor(new Color(255, 255, 128));
    graphics.fill(shape);
  }

}
