package GeneralSL.editor;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import org.jetbrains.annotations.Nullable;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.geom.GeneralPath;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import java.awt.Color;

public class Executor extends AbstractShape {
  private static final Logger LOG = LogManager.getLogger(Executor.class);


  public Executor() {
  }

  @Nullable
  @Override
  public Double getDefaultSize() {
    return ((double) (15));
  }



  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    GeneralPath shape = new GeneralPath();
    double width = bounds.getWidth();
    double height = bounds.getHeight();
    double x = bounds.getX() + width / 2;
    double y = bounds.getY() + height / 2;
    double r = 6;

    if (LOG.isInfoEnabled()) {
      LoggingRuntime.legacyLog(Level.INFO, "x " + x, Executor.class, null);
    }
    if (LOG.isInfoEnabled()) {
      LoggingRuntime.legacyLog(Level.INFO, "y " + y, Executor.class, null);
    }
    if (LOG.isInfoEnabled()) {
      LoggingRuntime.legacyLog(Level.INFO, "r " + r, Executor.class, null);
    }

    shape.moveTo(x - r, y);
    shape.lineTo(x, y - r);
    shape.lineTo(x + r, y);
    shape.lineTo(x, y + r);
    shape.closePath();
    graphics.setColor(Color.RED);
    graphics.fill(shape);
    graphics.draw(shape);

  }

}
