package Construction.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ActorRole_Constraints extends BaseConstraintsDescriptor {
  public ActorRole_Constraints() {
    super(MetaAdapterFactory.getConcept(0xd87481a388534c7cL, 0x9cb5096d805e832cL, 0x2613bb9aeaa032a9L, "Construction.structure.ActorRole"));
  }

}
